### ISSUE TITLE
return nil, err

### ISSUE THREAD

**Issue by vuknovakovicctd** [atfoc/parallel-dir-search#1]
`return nil, err` je nacin vracanje greske, ne panic
panic se oriste za neke doomsday scenarie(deljenje nulom, nil deref i sl)

**Comment by vuknovakovicctd** [comment]
Npr u onoj fji gde proveravas da li je unbounded queue init tu mi je ok `panic`, tamo gde listas dir samo vrati gresku, nema potrbe za `panic`-om

Generalno ako treba `panic`, std lib ce da ga vrati, ako std lib vrati `nil, err` u _vecini_ slucajeva ispratis i ti to

**Comment by atfoc** [comment]
Da da slazem se, fixovacu to tako sto cu vrv ispisati na stderror i progutati taj dir.
Ovo je ostalo samo iz prototipa jer mi je trebao brz nacin da vidim sta je to da li se desava i nisam hteo da razmisljam o tom case-u u tom trenutku.

**Comment by atfoc** [comment]
Fixed in this commit https://github.com/atfoc/parallel-dir-search/commit/789b03647cd09d97a11f0f1112fa673fb5040b60

**Comment by atfoc** [comment]
Reopen if you have more suggestions on this topic, and how is it handled

**Comment by atfoc** [comment]
https://github.com/atfoc/parallel-dir-search/commit/e676dc6647f9b6291537fe24bea23a43bcca5d2a
Forgot to skip this loop iter
